from data_structures import CountryElement


class Ukraine:
    def __init__(self):
        self.Cherkasy = CountryElement("Cherkasy")
        self.Chernihiv = CountryElement("Chernihiv")
        self.Chernivtsi = CountryElement("Chernivtsi")
        self.Crimea = CountryElement("Crimea")
        self.Dnipropetrovsk = CountryElement("Dnipropetrovsk")
        self.Donetsk = CountryElement("Donetsk")
        self.IvanoFrankivsk = CountryElement("Ivano-Frankivsk")
        self.Kharkiv = CountryElement("Kharkiv")
        self.Kherson = CountryElement("Kherson")
        self.Khmelnytskyi = CountryElement("Khmelnytskyi")
        self.Kiev = CountryElement("Kiev")
        self.Kirovohrad = CountryElement("Kirovohrad")
        self.Luhansk = CountryElement("Luhansk")
        self.Lviv = CountryElement("Lviv")
        self.Mykolaiv = CountryElement("Mykolaiv")
        self.Odessa = CountryElement("Odessa")
        self.Poltava = CountryElement("Poltava")
        self.Rivne = CountryElement("Rivne")
        self.Sumy = CountryElement("Sumy")
        self.Ternopil = CountryElement("Ternopil")
        self.Vinnytsia = CountryElement("Vinnytsia")
        self.Volyn = CountryElement("Volyn")
        self.Zakarpattia = CountryElement("Zakarpattia")
        self.Zaporizhia = CountryElement("Zaporizhia")
        self.Zhytomyr = CountryElement("Zhytomyr")

        self.Cherkasy.neighbours.append(self.Kiev)
        self.Cherkasy.neighbours.append(self.Poltava)
        self.Cherkasy.neighbours.append(self.Kirovohrad)
        self.Cherkasy.neighbours.append(self.Vinnytsia)

        self.Chernihiv.neighbours.append(self.Kiev)
        self.Chernihiv.neighbours.append(self.Sumy)
        self.Chernihiv.neighbours.append(self.Poltava)

        self.Chernivtsi.neighbours.append(self.IvanoFrankivsk)
        self.Chernivtsi.neighbours.append(self.Ternopil)
        self.Chernivtsi.neighbours.append(self.Khmelnytskyi)
        self.Chernivtsi.neighbours.append(self.Vinnytsia)

        self.Crimea.neighbours.append(self.Kherson)

        self.Dnipropetrovsk.neighbours.append(self.Poltava)
        self.Dnipropetrovsk.neighbours.append(self.Kharkiv)
        self.Dnipropetrovsk.neighbours.append(self.Donetsk)
        self.Dnipropetrovsk.neighbours.append(self.Zaporizhia)
        self.Dnipropetrovsk.neighbours.append(self.Kherson)
        self.Dnipropetrovsk.neighbours.append(self.Mykolaiv)
        self.Dnipropetrovsk.neighbours.append(self.Kirovohrad)

        self.Donetsk.neighbours.append(self.Luhansk)
        self.Donetsk.neighbours.append(self.Kharkiv)
        self.Donetsk.neighbours.append(self.Dnipropetrovsk)
        self.Donetsk.neighbours.append(self.Zaporizhia)

        self.IvanoFrankivsk.neighbours.append(self.Zakarpattia)
        self.IvanoFrankivsk.neighbours.append(self.Lviv)
        self.IvanoFrankivsk.neighbours.append(self.Ternopil)
        self.IvanoFrankivsk.neighbours.append(self.Chernivtsi)

        self.Kharkiv.neighbours.append(self.Sumy)
        self.Kharkiv.neighbours.append(self.Poltava)
        self.Kharkiv.neighbours.append(self.Dnipropetrovsk)
        self.Kharkiv.neighbours.append(self.Donetsk)
        self.Kharkiv.neighbours.append(self.Luhansk)

        self.Kherson.neighbours.append(self.Crimea)
        self.Kherson.neighbours.append(self.Zaporizhia)
        self.Kherson.neighbours.append(self.Dnipropetrovsk)
        self.Kherson.neighbours.append(self.Mykolaiv)

        self.Khmelnytskyi.neighbours.append(self.Vinnytsia)
        self.Khmelnytskyi.neighbours.append(self.Zhytomyr)
        self.Khmelnytskyi.neighbours.append(self.Rivne)
        self.Khmelnytskyi.neighbours.append(self.Ternopil)
        self.Khmelnytskyi.neighbours.append(self.Chernivtsi)

        self.Kiev.neighbours.append(self.Cherkasy)
        self.Kiev.neighbours.append(self.Chernihiv)
        self.Kiev.neighbours.append(self.Zhytomyr)
        self.Kiev.neighbours.append(self.Vinnytsia)

        self.Kirovohrad.neighbours.append(self.Mykolaiv)
        self.Kirovohrad.neighbours.append(self.Dnipropetrovsk)
        self.Kirovohrad.neighbours.append(self.Poltava)
        self.Kirovohrad.neighbours.append(self.Cherkasy)
        self.Kirovohrad.neighbours.append(self.Vinnytsia)
        self.Kirovohrad.neighbours.append(self.Odessa)

        self.Lviv.neighbours.append(self.Zakarpattia)
        self.Lviv.neighbours.append(self.IvanoFrankivsk)
        self.Lviv.neighbours.append(self.Ternopil)
        self.Lviv.neighbours.append(self.Rivne)
        self.Lviv.neighbours.append(self.Volyn)

        self.Luhansk.neighbours.append(self.Kharkiv)
        self.Luhansk.neighbours.append(self.Donetsk)

        self.Mykolaiv.neighbours.append(self.Odessa)
        self.Mykolaiv.neighbours.append(self.Kirovohrad)
        self.Mykolaiv.neighbours.append(self.Dnipropetrovsk)
        self.Mykolaiv.neighbours.append(self.Kherson)

        self.Odessa.neighbours.append(self.Vinnytsia)
        self.Odessa.neighbours.append(self.Kirovohrad)
        self.Odessa.neighbours.append(self.Mykolaiv)

        self.Poltava.neighbours.append(self.Dnipropetrovsk)
        self.Poltava.neighbours.append(self.Kharkiv)
        self.Poltava.neighbours.append(self.Sumy)
        self.Poltava.neighbours.append(self.Chernihiv)
        self.Poltava.neighbours.append(self.Cherkasy)
        self.Poltava.neighbours.append(self.Kirovohrad)

        self.Rivne.neighbours.append(self.Volyn)
        self.Rivne.neighbours.append(self.Lviv)
        self.Rivne.neighbours.append(self.Ternopil)
        self.Rivne.neighbours.append(self.Khmelnytskyi)
        self.Rivne.neighbours.append(self.Zhytomyr)

        self.Sumy.neighbours.append(self.Chernihiv)
        self.Sumy.neighbours.append(self.Poltava)
        self.Sumy.neighbours.append(self.Kharkiv)

        self.Ternopil.neighbours.append(self.Chernivtsi)
        self.Ternopil.neighbours.append(self.Khmelnytskyi)
        self.Ternopil.neighbours.append(self.Rivne)
        self.Ternopil.neighbours.append(self.Lviv)
        self.Ternopil.neighbours.append(self.IvanoFrankivsk)

        self.Vinnytsia.neighbours.append(self.Chernivtsi)
        self.Vinnytsia.neighbours.append(self.Khmelnytskyi)
        self.Vinnytsia.neighbours.append(self.Zhytomyr)
        self.Vinnytsia.neighbours.append(self.Kiev)
        self.Vinnytsia.neighbours.append(self.Cherkasy)
        self.Vinnytsia.neighbours.append(self.Kirovohrad)
        self.Vinnytsia.neighbours.append(self.Odessa)

        self.Volyn.neighbours.append(self.Lviv)
        self.Volyn.neighbours.append(self.Rivne)

        self.Zakarpattia.neighbours.append(self.Lviv)
        self.Zakarpattia.neighbours.append(self.IvanoFrankivsk)

        self.Zaporizhia.neighbours.append(self.Kherson)
        self.Zaporizhia.neighbours.append(self.Dnipropetrovsk)
        self.Zaporizhia.neighbours.append(self.Donetsk)

        self.Zhytomyr.neighbours.append(self.Rivne)
        self.Zhytomyr.neighbours.append(self.Khmelnytskyi)
        self.Zhytomyr.neighbours.append(self.Vinnytsia)
        self.Zhytomyr.neighbours.append(self.Kiev)

    def as_list(self):
        return [a for a in [getattr(self, attr) for attr in dir(self)] if isinstance(a, CountryElement)]


class USA: 
    def __init__(self):
        self.Alabama = CountryElement("Alabama")
        self.Arizona = CountryElement("Arizona")
        self.Arkansas = CountryElement("Arkansas")
        self.California = CountryElement("California")
        self.Colorado = CountryElement("Colorado")
        self.Connecticut = CountryElement("Connecticut")
        self.Delaware = CountryElement("Delaware")
        self.Florida = CountryElement("Florida")
        self.Georgia = CountryElement("Georgia")
        self.Idaho = CountryElement("Idaho")
        self.Illinois = CountryElement("Illinois")
        self.Indiana = CountryElement("Indiana")
        self.Iowa = CountryElement("Iowa")
        self.Kansas = CountryElement("Kansas")
        self.Kentucky = CountryElement("Kentucky")
        self.Louisiana = CountryElement("Louisiana")
        self.Maine = CountryElement("Maine")
        self.Maryland = CountryElement("Maryland")
        self.Massachusetts = CountryElement("Massachusetts")
        self.Michigan = CountryElement("Michigan")
        self.Minnesota = CountryElement("Minnesota")
        self.Mississippi = CountryElement("Mississippi")
        self.Missouri = CountryElement("Missouri")
        self.Montana = CountryElement("Montana")
        self.Nebraska = CountryElement("Nebraska")
        self.Nevada = CountryElement("Nevada")
        self.NewHampshire = CountryElement("New Hampshire")
        self.NewJersey = CountryElement("NewJersey")
        self.NewMexico = CountryElement("New Mexico")
        self.NewYork = CountryElement("New York")
        self.NorthCarolina = CountryElement("North Carolina")
        self.NorthDakota = CountryElement("North Dakota")
        self.Ohio = CountryElement("Ohio")
        self.Oklahoma = CountryElement("Oklahoma")
        self.Oregon = CountryElement("Oregon")
        self.Pennsylvania = CountryElement("Pennsylvania")
        self.RhodeIsland = CountryElement("Rhode Island")
        self.SouthCarolina = CountryElement("South Carolina")
        self.SouthDakota = CountryElement("South Dakota")
        self.Tennessee = CountryElement("Tennessee")
        self.Texas = CountryElement("Texas")
        self.Utah = CountryElement("Utah")
        self.Vermont = CountryElement("Vermont")
        self.Virginia = CountryElement("Virginia")
        self.Washington = CountryElement("Washington")
        self.WestVirginia = CountryElement("West Virginia")
        self.Wisconsin = CountryElement("Wisconsin")
        self.Wyoming = CountryElement("Wyoming")

        self.Alabama.neighbours.append(self.Florida)
        self.Alabama.neighbours.append(self.Georgia)
        self.Alabama.neighbours.append(self.Mississippi)
        self.Alabama.neighbours.append(self.Tennessee)
        
        self.Arizona.neighbours.append(self.California)
        self.Arizona.neighbours.append(self.Colorado)
        self.Arizona.neighbours.append(self.Nevada)
        self.Arizona.neighbours.append(self.NewMexico)
        self.Arizona.neighbours.append(self.Utah)
        
        self.Arkansas.neighbours.append(self.Louisiana)
        self.Arkansas.neighbours.append(self.Mississippi)
        self.Arkansas.neighbours.append(self.Missouri)
        self.Arkansas.neighbours.append(self.Oklahoma)
        self.Arkansas.neighbours.append(self.Tennessee)
        self.Arkansas.neighbours.append(self.Texas)
        
        self.California.neighbours.append(self.Arizona)
        self.California.neighbours.append(self.Nevada)
        self.California.neighbours.append(self.Oregon)
        
        self.Colorado.neighbours.append(self.Arizona)
        self.Colorado.neighbours.append(self.Kansas)
        self.Colorado.neighbours.append(self.Nebraska)
        self.Colorado.neighbours.append(self.NewMexico)
        self.Colorado.neighbours.append(self.Oklahoma)
        self.Colorado.neighbours.append(self.Utah)
        self.Colorado.neighbours.append(self.Wyoming)
        
        self.Connecticut.neighbours.append(self.Massachusetts)
        self.Connecticut.neighbours.append(self.NewYork)
        self.Connecticut.neighbours.append(self.RhodeIsland)
        
        self.Delaware.neighbours.append(self.Maryland)
        self.Delaware.neighbours.append(self.NewJersey)
        self.Delaware.neighbours.append(self.Pennsylvania)

        self.Florida.neighbours.append(self.Alabama)
        self.Florida.neighbours.append(self.Georgia)
        
        self.Georgia.neighbours.append(self.Alabama)
        self.Georgia.neighbours.append(self.Florida)
        self.Georgia.neighbours.append(self.NorthCarolina)
        self.Georgia.neighbours.append(self.SouthCarolina)
        self.Georgia.neighbours.append(self.Tennessee)
        
        self.Idaho.neighbours.append(self.Montana)
        self.Idaho.neighbours.append(self.Nevada)
        self.Idaho.neighbours.append(self.Oregon)
        self.Idaho.neighbours.append(self.Utah)
        self.Idaho.neighbours.append(self.Washington)
        self.Idaho.neighbours.append(self.Wyoming)
        
        self.Illinois.neighbours.append(self.Indiana)
        self.Illinois.neighbours.append(self.Iowa)
        self.Illinois.neighbours.append(self.Kentucky)
        self.Illinois.neighbours.append(self.Missouri)
        self.Illinois.neighbours.append(self.Wisconsin)
        
        self.Indiana.neighbours.append(self.Illinois)
        self.Indiana.neighbours.append(self.Kentucky)
        self.Indiana.neighbours.append(self.Michigan)
        self.Indiana.neighbours.append(self.Ohio)
        
        self.Iowa.neighbours.append(self.Illinois)
        self.Iowa.neighbours.append(self.Minnesota)
        self.Iowa.neighbours.append(self.Missouri)
        self.Iowa.neighbours.append(self.Nebraska)
        self.Iowa.neighbours.append(self.SouthDakota)
        self.Iowa.neighbours.append(self.Wisconsin)
        
        self.Kansas.neighbours.append(self.Colorado)
        self.Kansas.neighbours.append(self.Missouri)
        self.Kansas.neighbours.append(self.Nebraska)
        self.Kansas.neighbours.append(self.Oklahoma)
        
        self.Kentucky.neighbours.append(self.Illinois)
        self.Kentucky.neighbours.append(self.Indiana)
        self.Kentucky.neighbours.append(self.Missouri)
        self.Kentucky.neighbours.append(self.Ohio)
        self.Kentucky.neighbours.append(self.Tennessee)
        self.Kentucky.neighbours.append(self.Virginia)
        self.Kentucky.neighbours.append(self.WestVirginia)
        
        self.Louisiana.neighbours.append(self.Arkansas)
        self.Louisiana.neighbours.append(self.Mississippi)
        self.Louisiana.neighbours.append(self.Texas)
        
        self.Maine.neighbours.append(self.NewHampshire)
        
        self.Maryland.neighbours.append(self.Delaware)
        self.Maryland.neighbours.append(self.Pennsylvania)
        self.Maryland.neighbours.append(self.Virginia)
        self.Maryland.neighbours.append(self.WestVirginia)
        
        self.Massachusetts.neighbours.append(self.Connecticut)
        self.Massachusetts.neighbours.append(self.NewHampshire)
        self.Massachusetts.neighbours.append(self.NewYork)
        self.Massachusetts.neighbours.append(self.RhodeIsland)
        self.Massachusetts.neighbours.append(self.Vermont)
        
        self.Michigan.neighbours.append(self.Indiana)
        self.Michigan.neighbours.append(self.Ohio)
        self.Michigan.neighbours.append(self.Wisconsin)
        
        self.Minnesota.neighbours.append(self.Iowa)
        self.Minnesota.neighbours.append(self.NorthDakota)
        self.Minnesota.neighbours.append(self.SouthDakota)
        self.Minnesota.neighbours.append(self.Wisconsin)
        
        self.Mississippi.neighbours.append(self.Alabama)
        self.Mississippi.neighbours.append(self.Arkansas)
        self.Mississippi.neighbours.append(self.Louisiana)
        self.Mississippi.neighbours.append(self.Tennessee)
        
        self.Missouri.neighbours.append(self.Arkansas)
        self.Missouri.neighbours.append(self.Illinois)
        self.Missouri.neighbours.append(self.Iowa)
        self.Missouri.neighbours.append(self.Kansas)
        self.Missouri.neighbours.append(self.Kentucky)
        self.Missouri.neighbours.append(self.Nebraska)
        self.Missouri.neighbours.append(self.Oklahoma)
        self.Missouri.neighbours.append(self.Tennessee)
        
        self.Montana.neighbours.append(self.Idaho)
        self.Montana.neighbours.append(self.NorthDakota)
        self.Montana.neighbours.append(self.SouthDakota)
        self.Montana.neighbours.append(self.Wyoming)
        
        self.Nebraska.neighbours.append(self.Colorado)
        self.Nebraska.neighbours.append(self.Iowa)
        self.Nebraska.neighbours.append(self.Kansas)
        self.Nebraska.neighbours.append(self.Missouri)
        self.Nebraska.neighbours.append(self.SouthDakota)
        self.Nebraska.neighbours.append(self.Wyoming)
        
        self.Nevada.neighbours.append(self.Arizona)
        self.Nevada.neighbours.append(self.California)
        self.Nevada.neighbours.append(self.Idaho)
        self.Nevada.neighbours.append(self.Oregon)
        self.Nevada.neighbours.append(self.Utah)
        
        self.NewHampshire.neighbours.append(self.Maine)
        self.NewHampshire.neighbours.append(self.Massachusetts)
        self.NewHampshire.neighbours.append(self.Vermont)
        
        self.NewJersey.neighbours.append(self.Delaware)
        self.NewJersey.neighbours.append(self.NewYork)
        self.NewJersey.neighbours.append(self.Pennsylvania)
        
        self.NewMexico.neighbours.append(self.Arizona)
        self.NewMexico.neighbours.append(self.Colorado)
        self.NewMexico.neighbours.append(self.Oklahoma)
        self.NewMexico.neighbours.append(self.Texas)
        self.NewMexico.neighbours.append(self.Utah)
        
        self.NewYork.neighbours.append(self.Connecticut)
        self.NewYork.neighbours.append(self.Massachusetts)
        self.NewYork.neighbours.append(self.NewJersey)
        self.NewYork.neighbours.append(self.Pennsylvania)
        self.NewYork.neighbours.append(self.Vermont)
        
        self.NorthCarolina.neighbours.append(self.Georgia)
        self.NorthCarolina.neighbours.append(self.SouthCarolina)
        self.NorthCarolina.neighbours.append(self.Tennessee)
        self.NorthCarolina.neighbours.append(self.Virginia)
        
        self.NorthDakota.neighbours.append(self.Minnesota)
        self.NorthDakota.neighbours.append(self.Montana)
        self.NorthDakota.neighbours.append(self.SouthDakota)
        
        self.Ohio.neighbours.append(self.Indiana)
        self.Ohio.neighbours.append(self.Kentucky)
        self.Ohio.neighbours.append(self.Michigan)
        self.Ohio.neighbours.append(self.Pennsylvania)
        self.Ohio.neighbours.append(self.WestVirginia)
        
        self.Oklahoma.neighbours.append(self.Arkansas)
        self.Oklahoma.neighbours.append(self.Colorado)
        self.Oklahoma.neighbours.append(self.Kansas)
        self.Oklahoma.neighbours.append(self.Missouri)
        self.Oklahoma.neighbours.append(self.NewMexico)
        self.Oklahoma.neighbours.append(self.Texas)
        
        self.Oregon.neighbours.append(self.California)
        self.Oregon.neighbours.append(self.Idaho)
        self.Oregon.neighbours.append(self.Nevada)
        self.Oregon.neighbours.append(self.Washington)
        
        self.Pennsylvania.neighbours.append(self.Delaware)
        self.Pennsylvania.neighbours.append(self.Maryland)
        self.Pennsylvania.neighbours.append(self.NewJersey)
        self.Pennsylvania.neighbours.append(self.NewYork)
        self.Pennsylvania.neighbours.append(self.Ohio)
        self.Pennsylvania.neighbours.append(self.WestVirginia)
        
        self.RhodeIsland.neighbours.append(self.Connecticut)
        self.RhodeIsland.neighbours.append(self.Massachusetts)
        
        self.SouthCarolina.neighbours.append(self.Georgia)
        self.SouthCarolina.neighbours.append(self.NorthCarolina)
        
        self.SouthDakota.neighbours.append(self.Iowa)
        self.SouthDakota.neighbours.append(self.Minnesota)
        self.SouthDakota.neighbours.append(self.Montana)
        self.SouthDakota.neighbours.append(self.Nebraska)
        self.SouthDakota.neighbours.append(self.NorthDakota)
        self.SouthDakota.neighbours.append(self.Wyoming)
        
        self.Tennessee.neighbours.append(self.Alabama)
        self.Tennessee.neighbours.append(self.Arkansas)
        self.Tennessee.neighbours.append(self.Georgia)
        self.Tennessee.neighbours.append(self.Kentucky)
        self.Tennessee.neighbours.append(self.Mississippi)
        self.Tennessee.neighbours.append(self.Missouri)
        self.Tennessee.neighbours.append(self.NorthCarolina)
        self.Tennessee.neighbours.append(self.Virginia)
        
        self.Texas.neighbours.append(self.Arkansas)
        self.Texas.neighbours.append(self.Louisiana)
        self.Texas.neighbours.append(self.NewMexico)
        self.Texas.neighbours.append(self.Oklahoma)
        
        self.Utah.neighbours.append(self.Arizona)
        self.Utah.neighbours.append(self.Colorado)
        self.Utah.neighbours.append(self.Idaho)
        self.Utah.neighbours.append(self.Nevada)
        self.Utah.neighbours.append(self.NewMexico)
        self.Utah.neighbours.append(self.Wyoming)
        
        self.Vermont.neighbours.append(self.Massachusetts)
        self.Vermont.neighbours.append(self.NewHampshire)
        self.Vermont.neighbours.append(self.NewYork)

        self.Virginia.neighbours.append(self.Kentucky)
        self.Virginia.neighbours.append(self.Maryland)
        self.Virginia.neighbours.append(self.NorthCarolina)
        self.Virginia.neighbours.append(self.Tennessee)
        self.Virginia.neighbours.append(self.WestVirginia)
        
        self.Washington.neighbours.append(self.Idaho)
        self.Washington.neighbours.append(self.Oregon)
        
        self.WestVirginia.neighbours.append(self.Kentucky)
        self.WestVirginia.neighbours.append(self.Maryland)
        self.WestVirginia.neighbours.append(self.Ohio)
        self.WestVirginia.neighbours.append(self.Pennsylvania)
        self.WestVirginia.neighbours.append(self.Virginia)
        
        self.Wisconsin.neighbours.append(self.Illinois)
        self.Wisconsin.neighbours.append(self.Iowa)
        self.Wisconsin.neighbours.append(self.Michigan)
        self.Wisconsin.neighbours.append(self.Minnesota)
        
        self.Wyoming.neighbours.append(self.Colorado)
        self.Wyoming.neighbours.append(self.Idaho)
        self.Wyoming.neighbours.append(self.Montana)
        self.Wyoming.neighbours.append(self.Nebraska)
        self.Wyoming.neighbours.append(self.SouthDakota)
        self.Wyoming.neighbours.append(self.Utah)
    
    def as_list(self):
        return [a for a in [getattr(self, attr) for attr in dir(self)] if isinstance(a, CountryElement)]


class China: 
    def __init__(self):
        self.AnhuiProvince = CountryElement("Anhui Province")
        self.BeijingMunicipality = CountryElement("Beijing Municipality")
        self.ChongqingMunicipality = CountryElement("Chongqing Municipality")
        self.FujianProvince = CountryElement("Fujian Province")
        self.GansuProvince = CountryElement("Gansu Province")
        self.GuangdongProvince = CountryElement("Guangdong Province")
        self.GuangxiZhuangAutonomousRegion = CountryElement("Guangxi Zhuang Autonomous Region")
        self.GuizhouProvince = CountryElement("Guizhou Province")
        self.HebeiProvince = CountryElement("Hebei Province")
        self.HeilongjiangProvince = CountryElement("Heilongjiang Province")
        self.HenanProvince = CountryElement("Henan Province")
        self.HongKongSpecialAdministrativeRegion = CountryElement("Hong Kong Special Administrative Region")
        self.HubeiProvince = CountryElement("Hubei Province")
        self.HunanProvince = CountryElement("Hunan Province")
        self.InnerMongoliaAutonomousRegion = CountryElement("Inner Mongolia Autonomous Region")
        self.JiangsuProvince = CountryElement("Jiangsu Province")
        self.JiangxiProvince = CountryElement("Jiangxi Province")
        self.JilinProvince = CountryElement("Jilin Province")
        self.LiaoningProvince = CountryElement("Liaoning Province")
        self.Macau = CountryElement("Macau")
        self.NingxiaHuiAutonomousRegion = CountryElement("Ningxia Hui Autonomous Region")
        self.QinghaiProvince = CountryElement("Qinghai Province")
        self.ShaanxiProvince = CountryElement("Shaanxi Province")
        self.ShandongProvince = CountryElement("Shandong Province")
        self.ShanghaiMunicipality = CountryElement("Shanghai Municipality")
        self.ShanxiProvince = CountryElement("Shanxi Province")
        self.SichuanProvince = CountryElement("Sichuan Province")
        self.TianjinMunicipality = CountryElement("Tianjin Municipality")
        self.TibetAutonomousRegion = CountryElement("Tibet Autonomous Region")
        self.XinjiangUyghurAutonomousRegion = CountryElement("Xinjiang Uyghur Autonomous Region")
        self.YunnanProvince = CountryElement("Yunnan Province")
        self.ZhejiangProvince = CountryElement("Zhejiang Province")

        self.AnhuiProvince.neighbours.append(self.HenanProvince)
        self.AnhuiProvince.neighbours.append(self.HubeiProvince)
        self.AnhuiProvince.neighbours.append(self.JiangsuProvince)
        self.AnhuiProvince.neighbours.append(self.JiangxiProvince)
        self.AnhuiProvince.neighbours.append(self.ShandongProvince)
        self.AnhuiProvince.neighbours.append(self.ZhejiangProvince)

        self.BeijingMunicipality.neighbours.append(self.HebeiProvince)
        self.BeijingMunicipality.neighbours.append(self.TianjinMunicipality)

        self.ChongqingMunicipality.neighbours.append(self.GuizhouProvince)
        self.ChongqingMunicipality.neighbours.append(self.HubeiProvince)
        self.ChongqingMunicipality.neighbours.append(self.HunanProvince)
        self.ChongqingMunicipality.neighbours.append(self.ShaanxiProvince)
        self.ChongqingMunicipality.neighbours.append(self.SichuanProvince)

        self.FujianProvince.neighbours.append(self.GuangdongProvince)
        self.FujianProvince.neighbours.append(self.JiangxiProvince)
        self.FujianProvince.neighbours.append(self.ZhejiangProvince)

        self.GansuProvince.neighbours.append(self.InnerMongoliaAutonomousRegion)
        self.GansuProvince.neighbours.append(self.NingxiaHuiAutonomousRegion)
        self.GansuProvince.neighbours.append(self.QinghaiProvince)
        self.GansuProvince.neighbours.append(self.ShaanxiProvince)
        self.GansuProvince.neighbours.append(self.SichuanProvince)
        self.GansuProvince.neighbours.append(self.XinjiangUyghurAutonomousRegion)

        self.GuangdongProvince.neighbours.append(self.FujianProvince)
        self.GuangdongProvince.neighbours.append(self.GuangxiZhuangAutonomousRegion)
        self.GuangdongProvince.neighbours.append(self.HongKongSpecialAdministrativeRegion)
        self.GuangdongProvince.neighbours.append(self.HunanProvince)
        self.GuangdongProvince.neighbours.append(self.JiangxiProvince)
        self.GuangdongProvince.neighbours.append(self.Macau)

        self.GuangxiZhuangAutonomousRegion.neighbours.append(self.GuangdongProvince)
        self.GuangxiZhuangAutonomousRegion.neighbours.append(self.GuizhouProvince)
        self.GuangxiZhuangAutonomousRegion.neighbours.append(self.HunanProvince)
        self.GuangxiZhuangAutonomousRegion.neighbours.append(self.YunnanProvince)

        self.GuizhouProvince.neighbours.append(self.ChongqingMunicipality)
        self.GuizhouProvince.neighbours.append(self.GuangxiZhuangAutonomousRegion)
        self.GuizhouProvince.neighbours.append(self.HunanProvince)
        self.GuizhouProvince.neighbours.append(self.SichuanProvince)
        self.GuizhouProvince.neighbours.append(self.YunnanProvince)

        self.HebeiProvince.neighbours.append(self.BeijingMunicipality)
        self.HebeiProvince.neighbours.append(self.HenanProvince)
        self.HebeiProvince.neighbours.append(self.InnerMongoliaAutonomousRegion)
        self.HebeiProvince.neighbours.append(self.LiaoningProvince)
        self.HebeiProvince.neighbours.append(self.ShandongProvince)
        self.HebeiProvince.neighbours.append(self.ShanxiProvince)
        self.HebeiProvince.neighbours.append(self.TianjinMunicipality)

        self.HeilongjiangProvince.neighbours.append(self.InnerMongoliaAutonomousRegion)
        self.HeilongjiangProvince.neighbours.append(self.JilinProvince)

        self.HenanProvince.neighbours.append(self.AnhuiProvince)
        self.HenanProvince.neighbours.append(self.ShandongProvince)
        self.HenanProvince.neighbours.append(self.ShanxiProvince)

        self.HongKongSpecialAdministrativeRegion.neighbours.append(self.GuangdongProvince)

        self.HubeiProvince.neighbours.append(self.AnhuiProvince)
        self.HubeiProvince.neighbours.append(self.ChongqingMunicipality)
        self.HubeiProvince.neighbours.append(self.HenanProvince)
        self.HubeiProvince.neighbours.append(self.HunanProvince)
        self.HubeiProvince.neighbours.append(self.JiangxiProvince)
        self.HubeiProvince.neighbours.append(self.ShaanxiProvince)

        self.HunanProvince.neighbours.append(self.ChongqingMunicipality)
        self.HunanProvince.neighbours.append(self.GuangdongProvince)
        self.HunanProvince.neighbours.append(self.GuangxiZhuangAutonomousRegion)
        self.HunanProvince.neighbours.append(self.GuizhouProvince)
        self.HunanProvince.neighbours.append(self.HubeiProvince)
        self.HunanProvince.neighbours.append(self.JiangxiProvince)

        self.InnerMongoliaAutonomousRegion.neighbours.append(self.GansuProvince)
        self.InnerMongoliaAutonomousRegion.neighbours.append(self.HebeiProvince)
        self.InnerMongoliaAutonomousRegion.neighbours.append(self.HeilongjiangProvince)
        self.InnerMongoliaAutonomousRegion.neighbours.append(self.JilinProvince)
        self.InnerMongoliaAutonomousRegion.neighbours.append(self.LiaoningProvince)
        self.InnerMongoliaAutonomousRegion.neighbours.append(self.NingxiaHuiAutonomousRegion)
        self.InnerMongoliaAutonomousRegion.neighbours.append(self.ShaanxiProvince)
        self.InnerMongoliaAutonomousRegion.neighbours.append(self.ShanxiProvince)

        self.JiangsuProvince.neighbours.append(self.AnhuiProvince)
        self.JiangsuProvince.neighbours.append(self.ShandongProvince)
        self.JiangsuProvince.neighbours.append(self.ShanghaiMunicipality)
        self.JiangsuProvince.neighbours.append(self.ZhejiangProvince)

        self.JiangxiProvince.neighbours.append(self.AnhuiProvince)
        self.JiangxiProvince.neighbours.append(self.FujianProvince)
        self.JiangxiProvince.neighbours.append(self.GuangdongProvince)
        self.JiangxiProvince.neighbours.append(self.HubeiProvince)
        self.JiangxiProvince.neighbours.append(self.HunanProvince)
        self.JiangxiProvince.neighbours.append(self.ZhejiangProvince)

        self.JilinProvince.neighbours.append(self.HeilongjiangProvince)
        self.JilinProvince.neighbours.append(self.InnerMongoliaAutonomousRegion)
        self.JilinProvince.neighbours.append(self.LiaoningProvince)

        self.LiaoningProvince.neighbours.append(self.HebeiProvince)
        self.LiaoningProvince.neighbours.append(self.InnerMongoliaAutonomousRegion)
        self.LiaoningProvince.neighbours.append(self.JilinProvince)

        self.Macau.neighbours.append(self.GuangdongProvince)

        self.NingxiaHuiAutonomousRegion.neighbours.append(self.GansuProvince)
        self.NingxiaHuiAutonomousRegion.neighbours.append(self.InnerMongoliaAutonomousRegion)
        self.NingxiaHuiAutonomousRegion.neighbours.append(self.ShaanxiProvince)

        self.QinghaiProvince.neighbours.append(self.GansuProvince)
        self.QinghaiProvince.neighbours.append(self.SichuanProvince)
        self.QinghaiProvince.neighbours.append(self.TibetAutonomousRegion)
        self.QinghaiProvince.neighbours.append(self.XinjiangUyghurAutonomousRegion)

        self.ShaanxiProvince.neighbours.append(self.ChongqingMunicipality)
        self.ShaanxiProvince.neighbours.append(self.GansuProvince)
        self.ShaanxiProvince.neighbours.append(self.HenanProvince)
        self.ShaanxiProvince.neighbours.append(self.HubeiProvince)
        self.ShaanxiProvince.neighbours.append(self.InnerMongoliaAutonomousRegion)
        self.ShaanxiProvince.neighbours.append(self.NingxiaHuiAutonomousRegion)
        self.ShaanxiProvince.neighbours.append(self.ShanxiProvince)
        self.ShaanxiProvince.neighbours.append(self.SichuanProvince)

        self.ShandongProvince.neighbours.append(self.AnhuiProvince)
        self.ShandongProvince.neighbours.append(self.HebeiProvince)
        self.ShandongProvince.neighbours.append(self.HenanProvince)
        self.ShandongProvince.neighbours.append(self.JiangsuProvince)

        self.ShanghaiMunicipality.neighbours.append(self.JiangsuProvince)
        self.ShanghaiMunicipality.neighbours.append(self.ZhejiangProvince)

        self.ShanxiProvince.neighbours.append(self.HebeiProvince)
        self.ShanxiProvince.neighbours.append(self.HenanProvince)
        self.ShanxiProvince.neighbours.append(self.InnerMongoliaAutonomousRegion)
        self.ShanxiProvince.neighbours.append(self.ShaanxiProvince)

        self.SichuanProvince.neighbours.append(self.ChongqingMunicipality)
        self.SichuanProvince.neighbours.append(self.GansuProvince)
        self.SichuanProvince.neighbours.append(self.GuizhouProvince)
        self.SichuanProvince.neighbours.append(self.QinghaiProvince)
        self.SichuanProvince.neighbours.append(self.ShaanxiProvince)
        self.SichuanProvince.neighbours.append(self.TibetAutonomousRegion)
        self.SichuanProvince.neighbours.append(self.YunnanProvince)

        self.TianjinMunicipality.neighbours.append(self.BeijingMunicipality)
        self.TianjinMunicipality.neighbours.append(self.HebeiProvince)

        self.TibetAutonomousRegion.neighbours.append(self.QinghaiProvince)
        self.TibetAutonomousRegion.neighbours.append(self.SichuanProvince)
        self.TibetAutonomousRegion.neighbours.append(self.XinjiangUyghurAutonomousRegion)
        self.TibetAutonomousRegion.neighbours.append(self.YunnanProvince)

        self.XinjiangUyghurAutonomousRegion.neighbours.append(self.GansuProvince)
        self.XinjiangUyghurAutonomousRegion.neighbours.append(self.QinghaiProvince)
        self.XinjiangUyghurAutonomousRegion.neighbours.append(self.TibetAutonomousRegion)

        self.YunnanProvince.neighbours.append(self.GuangxiZhuangAutonomousRegion)
        self.YunnanProvince.neighbours.append(self.GuizhouProvince)
        self.YunnanProvince.neighbours.append(self.SichuanProvince)
        self.YunnanProvince.neighbours.append(self.TibetAutonomousRegion)

        self.ZhejiangProvince.neighbours.append(self.AnhuiProvince)
        self.ZhejiangProvince.neighbours.append(self.FujianProvince)
        self.ZhejiangProvince.neighbours.append(self.JiangsuProvince)
        self.ZhejiangProvince.neighbours.append(self.JiangxiProvince)
        self.ZhejiangProvince.neighbours.append(self.ShanghaiMunicipality)

    def as_list(self):
        return [a for a in [getattr(self, attr) for attr in dir(self)] if isinstance(a, CountryElement)]