class USA: 
	def __init__(self):
		self.Alabama = CountryElement("Alabama")
		self.Alaska = CountryElement("Alaska")
		self.Arizona = CountryElement("Arizona")
		self.Arkansas = CountryElement("Arkansas")
		self.California = CountryElement("California")
		self.Colorado = CountryElement("Colorado")
		self.Connecticut = CountryElement("Connecticut")
		self.Delaware = CountryElement("Delaware")
		self.Florida = CountryElement("Florida")
		self.Georgia = CountryElement("Georgia")
		self.Hawaii = CountryElement("Hawaii")
		self.Idaho = CountryElement("Idaho")
		self.Illinois = CountryElement("Illinois")
		self.Indiana = CountryElement("Indiana")
		self.Iowa = CountryElement("Iowa")
		self.Kansas = CountryElement("Kansas")
		self.Kentucky = CountryElement("Kentucky")
		self.Louisiana = CountryElement("Louisiana")
		self.Maine = CountryElement("Maine")
		self.Maryland = CountryElement("Maryland")
		self.Massachussetts = CountryElement("Massachussetts")
		self.Michigan = CountryElement("Michigan")
		self.Minnesota = CountryElement("Minnesota")
		self.Mississippi = CountryElement("Mississippi")
		self.Missouri = CountryElement("Missouri")
		self.Montana = CountryElement("Montana")
		self.Nebraska = CountryElement("Nebraska")
		self.Nevada = CountryElement("Nevada")
		self.NewHampshire = CountryElement("New Hampshire")
		self.NewJersey = CountryElement("NewJersey")
		self.NewMexico = CountryElement("New Mexico")
		self.NewYork = CountryElement("New York")
		self.NorthCarolina = CountryElement("North Carolina")
		self.NorthDakota = CountryElement("North Dakota")
		self.Ohio = CountryElement("Ohio")
		self.Oklahoma = CountryElement("Oklahoma")
		self.Oregon = CountryElement("Oregon")
		self.Pennsylvania = CountryElement("Pennsylvania")
		self.RhodeIsland = CountryElement("Rhode Island")
		self.SouthCarolina = CountryElement("South Carolina")
		self.SouthDakota = CountryElement("South Dakota")
		self.Tennessee = CountryElement("Tennessee")
		self.Texas = CountryElement("Texas")
		self.Utah = CountryElement("Utah")
		self.Vermont = CountryElement("Vermont")
		self.Virginia = CountryElement("Virginia")
		self.Washington = CountryElement("Washington")
		self.WestVirginia = CountryElement("West Virginia")
		self.Wisconsin = CountryElement("Wisconsin")
		self.Wyoming = CountryElement("Wyoming")





